run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: "NO"
        subdir: kl/CorrectBench
    log: 
        debug_en: False
gpt: 
    model: gpt-4o-mini-2024-07-18
    rtlgen_model: gpt-4o-mini-2024-07-18
autoline: 
    probset: 
        path: data/HDLBits/wrapped-kl-dataset.jsonl
    promptscript: pychecker
    timeout: 40
    save_compile: False
    debug: 
        max: 1
    itermax: 1
    update_desc: False
    TBcheck: 
        discrim_mode: col_70_wrong_row_25_correct
